---
- name: Deploy ping_exporter on VMs
  hosts: all
  become: yes
  vars:
#    ping_exporter_version: "1.1.3"
    ping_exporter_port: 9568
    ping_target: "192.168.87.50"

  tasks:
    - name: Download ping_exporter binary
      get_url:
        url: "https://github.com/czerwonk/ping_exporter/releases/download/1.1.3/ping_exporter_1.1.3_linux_amd64.tar.gz"
        dest: /tmp/ping_exporter.tar.gz

    - name: Extract ping_exporter
      unarchive:
        src: /tmp/ping_exporter.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Make ping_exporter executable
      file:
        path: /usr/local/bin/ping_exporter
        mode: '0755'

    - name: Create ping_exporter user
      user:
        name: pingexporter
        system: yes
        shell: /sbin/nologin

    - name: Create systemd service file for ping_exporter
      copy:
        dest: /etc/systemd/system/ping_exporter.service
        content: |
          [Unit]
          Description=Prometheus Ping Exporter
          After=network.target

          [Service]
          User=pingexporter
          ExecStart=/usr/local/bin/ping_exporter --web.listen-address=:{{ ping_exporter_port }} --hosts={{ ping_target }}
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start ping_exporter service
      systemd:
        name: ping_exporter
        state: started
        enabled: yes
