---
- name: Perform project tasks
  hosts: all
  become: yes
  tasks:
    - name: Move to project directory
      shell: cd /var/intellicon

    - name: Check git branch
      shell: git branch --show-current
      register: git_branch_result

    - name: Check if branch is production_tag
      fail:
        msg: "Branch is not set as production_tag"
      when: git_branch_result.stdout != "production_tag"

    - name: Git pull
      ignore_errors: yes
      shell: git pull
      register: git_pull_result

    - name: Fail if there are conflicts
      fail:
        msg: "Git pull resulted in conflicts"
      when: "'CONFLICT' in git_pull_result.stderr"

    - name: Docker compose pull
      shell: docker-compose pull

    - name: Stop and remove intellicon_modules container
      shell: docker rm -f intellicon_modules || true

    - name: Recreate intellicon_modules container
      shell: docker-compose up -d --force-recreate intellicon_modules

    - name: Recreate migration container
      shell: docker-compose up -d --force-recreate migration

    - name: Display logs of migration container
      shell: docker-compose logs -f migration

    - name: Wait for migration container to exit
      async: 100
      poll: 0
      shell: sleep 0

    - name: Docker compose down
      shell: docker-compose down

    - name: Wait for 2 minutes
      pause:
        seconds: 120

    - name: Docker compose up
      shell: docker-compose up -d
