---
- name: Perform project tasks
  hosts: all
  become: yes
  tasks:
    - name: Check git branch
      shell: "cd /var/intellicon && git branch --show-current"
      register: git_branch_result

    - name: Check if branch is production_tag
      fail:
        msg: "Branch is not set as production_tag"
      when: git_branch_result.stdout | trim != "production_tag"

    - name: Git pull
      shell: "cd /var/intellicon && sudo git pull"
      register: git_pull_result
      ignore_errors: yes

    - name: Fail if there are conflicts
      fail:
        msg: "Git pull resulted in conflicts"
      when: "'CONFLICT' in git_pull_result.stderr"
    
    - name: Docker compose pull
      shell: "cd /var/intellicon && INTELLICON_VERSION=3.0.32 docker compose pull"

    - name: Stop and remove intellicon_modules container
      shell: "cd /var/intellicon && docker rm -f intellicon_modules || true"

    - name: Recreate intellicon_modules container
      shell: "cd /var/intellicon && docker compose up -d --force-recreate intellicon_modules"

    - name: Recreate migration container
      shell: "cd /var/intellicon && docker compose up -d --force-recreate migration"

    - name: Display logs of migration container
      shell: "cd /var/intellicon && docker-compose logs -f migration"

    - name: Wait for migration container to exit
      async: 100
      poll: 0
      shell: "cd /var/intellicon && sleep 0"

    - name: Docker compose down
      shell: "cd /var/intellicon && docker compose down"

    - name: Wait for 2 minutes
      pause:
        seconds: 120

    - name: Docker compose up
      shell: "cd /var/intellicon && docker compose up -d"
